[WIP] test(workflow): fix yarn tests
opensbom-generator/parsers pull request #58
Opened 2023-05-26 16:53 UTC by ba11b0y

Fixes #57

2023-05-30 08:01 UTC, cpanato requested changes
thanks for the update!

see some small comments

2023-05-30 08:01 UTC, cpanato commented on .github/workflows/test.yml
> +        uses: actions/setup-node@v3
can you please use the git hash for the latest release? similar we have for the others, thanks!

2023-05-30 08:01 UTC, cpanato commented on .github/workflows/test.yml
> +        uses: borales/actions-yarn@v4
same here

2023-05-30 08:02 UTC, cpanato commented
cc @puerco

2023-05-30 18:53 UTC, ba11b0y commented
Thanks for the review @cpanato 
Pushed https://github.com/opensbom-generator/parsers/pull/58/commits/ab705f360acca3c9548fba5e41bf75c9a0b4112e

Also can you approve the workflow(first-time contributor here) so that I can test the PR
Ref: https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks

2023-05-30 19:11 UTC, cpanato commented on .github/workflows/test.yml
> +        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
Please add a version in a comment in the same line. See the above for example

Thanks

2023-05-31 07:34 UTC, cpanato reviewed
thanks!

2023-05-31 07:35 UTC, cpanato commented
need you here @puerco to approve the CI and PR

2023-05-31 14:03 UTC, nishakm commented
@cpanato @ba11b0y I was expecting `go test -v` to run for  this PR, but I guess if it doesn't, I can test it on another PR. Otherwise LGTM!

2023-05-31 14:04 UTC, merged